"""Add login tracking

Revision ID: 54d2f984deec
Revises: a9dc0e1e6163
Create Date: 2025-10-31 07:36:21.924835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '54d2f984deec'
down_revision: Union[str, None] = 'a9dc0e1e6163'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userloginhistory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('login_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_userloginhistory_login_time'), 'userloginhistory', ['login_time'], unique=False)
    op.create_index(op.f('ix_userloginhistory_user_id'), 'userloginhistory', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_userloginhistory_user_id'), table_name='userloginhistory')
    op.drop_index(op.f('ix_userloginhistory_login_time'), table_name='userloginhistory')
    op.drop_table('userloginhistory')
    # ### end Alembic commands ###
