"""Subscription

Revision ID: 67dc8e7b1929
Revises: d57e9b32607b
Create Date: 2025-10-28 10:03:07.556881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '67dc8e7b1929'
down_revision: Union[str, None] = 'd57e9b32607b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('endpoint', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=False),
    sa.Column('p256dh', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('auth', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_auth'), 'subscriptions', ['auth'], unique=False)
    op.create_index(op.f('ix_subscriptions_endpoint'), 'subscriptions', ['endpoint'], unique=False)
    op.create_index(op.f('ix_subscriptions_p256dh'), 'subscriptions', ['p256dh'], unique=False)
    op.create_index(op.f('ix_subscriptions_username'), 'subscriptions', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscriptions_username'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_p256dh'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_endpoint'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_auth'), table_name='subscriptions')
    op.drop_table('subscriptions')
    # ### end Alembic commands ###
