"""Add field in the clinics table

Revision ID: dc597bb4127c
Revises: 54d2f984deec
Create Date: 2025-10-31 08:03:22.228720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'dc597bb4127c'
down_revision: Union[str, None] = '54d2f984deec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clinics', sa.Column('opening_hours', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('clinics', sa.Column('cost', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clinics', 'cost')
    op.drop_column('clinics', 'opening_hours')
    # ### end Alembic commands ###
